// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

const (
	Type                      = "sum"
	TracesToMetricsStability  = component.StabilityLevelDevelopment
	MetricsToMetricsStability = component.StabilityLevelDevelopment
	LogsToMetricsStability    = component.StabilityLevelDevelopment
)
